### ISSUE TITLE
 write code to take parameters/arguments for runs from some master table we can easily edit, and use that as input args for doRun

### ISSUE THREAD

**Issue by dwbapst** [bomeara/treevo_paper#3]
This may be complicated by how we want to set up each of these 'larger' chunks of analysis-runs on clusters and thus am assigning to both me and @bomeara

**Comment by bomeara** [comment]
This is how I'm thinking of doing it: https://ropenscilabs.github.io/drake-manual/plans.html#wildcard-clusters

**Comment by dwbapst** [comment]
Yeah, we didn't do it exactly like Drake, but its similar in some ways. Either way, this is done.
