### ISSUE TITLE
run some simulations with aquilegia models

### ISSUE THREAD

**Issue by dwbapst** [bomeara/treevo_paper#4]
Need to make sure it does something like what I expect it to be doing

**Comment by dwbapst** [comment]
Well, I'd say that worked!

```
# 3 bounds, 3 optima with weak-ish attraction
params<-c(
	sigma=0.1,
	alpha=0.3,
	rho=1,
	maxbounds=c(20,40,60),
	theta=c(10,30,50)
	)	
		
repSim<-replicate(300,
	repeatSimSteps(params,trait = 0, nSteps = 100, 
		fun = multiOptima3IntrinsicMaxBoudary3
		)
	)
hist(repSim,main="Simulated Trait Values",breaks=20)
```

**Comment by dwbapst** [comment]
![image](https://user-images.githubusercontent.com/1561903/46776653-32116780-ccd2-11e8-8478-899a832c2759.png)

**Comment by dwbapst** [comment]
![image](https://user-images.githubusercontent.com/1561903/46776963-7b15eb80-ccd3-11e8-8dc7-4627046ae3e2.png)

From:

```
# 2 bounds, 3 optima with weak attraction relative to diffusion
params<-c(
	sigma=0.7,
	alpha=0.1,
	rho=0.5,
	maxbounds=c(20,40),
	theta=c(10,30,50)
	)	
	
repSim<-replicate(300,
	repeatSimSteps(params,trait = 0, nSteps = 100, 
		fun = multiOptima3IntrinsicMaxBoudary2
		)
	)
hist(repSim,main="Simulated Trait Values",breaks=20)
```

**Comment by dwbapst** [comment]
And if I make inertia (rho, which negatively impacts transition) too low, or diffusion too low, or alpha too high, we get a histogram centered on the maximum optimum... 

![image](https://user-images.githubusercontent.com/1561903/46777088-efe92580-ccd3-11e8-930b-0efe477b4540.png)

**Comment by dwbapst** [comment]
so I would say these models work great

**Comment by bomeara** [comment]
I agree
